<?php
/**
 * 描述：
 * Created at 2021/3/16 8:44 by 陈庙琴
 */

namespace oba_mui_style\libs\trait_set;


use epii\server\Tools;
use oba_mui_style\libs\EpiiMViewEngine;

trait MTrait
{
    public function init()
    {
        $engine = new EpiiMViewEngine();
        $engine->init(["tpl_dir" => Tools::getVendorDir() . "/../view/", "cache_dir" => Tools::getVendorDir() . "/../runtime/cache/view/", 'replace_key' => '<?php include $tmpfile;?>']);
        $this->setViewEngine($engine);
        parent::init(); // TODO: Change the autogenerated stub
    }
}