<?php
/**
 * 描述：
 * Created at 2021/3/15 19:30 by 陈庙琴
 */

namespace oba_mui_style;


use epii\app\controller;
use epii\server\Tools;
use oba_mui_style\libs\EpiiMViewEngine;

class mui_controller extends controller
{
    public function init()
    {
        $engine = new EpiiMViewEngine();
        $engine->init(["tpl_dir" => Tools::getVendorDir() . "/../view/", "cache_dir" => Tools::getVendorDir() . "/../runtime/cache/view/", 'replace_key' => '<?php include $tmpfile;?>']);
        $this->setViewEngine($engine);
        parent::init(); // TODO: Change the autogenerated stub
    }
}